[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
#linker = "/opt/riscv/bin/riscv64-unknown-linux-gnu-gcc"
rustflags = [
    "-C", "link-arg=-Tkernel.ld"
]

# From xv6-riscv project Makefile.
#    """
#    qemu-system-riscv64 \
#    -machine virt -bios none \
#    -m 1G -smp 2 -nographic \
#    -drive file=fs.img,if=none,format=raw,id=x0 \
#    -device virtio-blk-device,drive=x0,bus=virtio-mmio-bus.0 \
#    -kernel
#    """
