[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "riscv64imac-unknown-none-elf"
rustflags = ["-C", "link-args=-Tkernel.ld"]

[target.riscv64imac-unknown-none-elf]
runner = "./qemu-wrapper.sh riscv64"
